language: python

cache: pip

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - cd /home/travis/build/makism/dyfunconn/tests/
  - nosetests --cover-tests --with-coverage --cover-package=dyfunconn

after_success:
  - coveralls
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codecov
