language: python

cache: pip

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - cd /home/travis/build/makism/dyconnmap/tests/
  - nosetests --cover-tests --with-coverage --cover-package=dyconnmap

after_success:
  - coveralls
  - coverage xml
  - wget -qO - https://coverage.codacy.com/get.sh | sh -s report -l Python -r coverage.xml  final
  - codecov
