name: publish-test-pypi

on: push

jobs:
  build:
    name: Build and publish on TestPyPI
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@master
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Print tag
        run: |
          echo $RELEASE_VERSION > TAG_VERSION
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install setuptools
        run: >-
          python -m pip install setuptools --user
      - name: Install wheels
        run: >-
          python -m pip install wheel --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python setup_tag.py sdist bdist_wheel
      - name: Publish distribution to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          username: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
